In [ ]:
#variable
a=10
print("i am",a,"years old")

i am 10 years old


In [ ]:
a=(int)(input("enter a value"))    #arthemetic operations of two number
b=(int)(input("enter b value"))
print("sum=",a+b)
print("diff=",a-b)
print("prod=",a*b)
print("div=",a/b)
print("mod=",a%b)
print("power=",pow(a,b))

enter a value233
enter b value44
sum= 277
diff= 189
prod= 10252
div= 5.295454545454546
mod= 13
power= 145767439486761302818642692512645511859113355390863877966683490033485698479325373731167061782089423642721


In [ ]:
#take a number from user which is sal if sal is more than 50K there is 10% tax print his final salary
a=int(input("enter your salary"))
c=a*10/100
if a>=50000:
      v=a-c
      print("salary after all taxes=",v)
else:
      print("salary is without taxes:",a)


enter your salary60555
salary after all taxes= 54499.5


In [ ]:
 #get salary from the user if salary is more than or equal to 50k then apply 10% tax reduction if salary<50K apply 5% tax if the salary is >70K apply 12% tax if salary excedes 1 lakh print you are promoted to next level
 sal=int(input("enter salary"))
 if sal<50000:
      tax=sal*5/100
      sal=sal-tax
      print("salary after 5% 0f tax=",sal)
 elif sal>=50000 and sal<7 0000:
      tax=sal*10/100
      sal=sal-tax
      print("salary after 10% 0f tax=",sal)
 elif sal>=70000 and sal<100000:
      tax=sal*12/100
      sal=sal-tax
      print("salary after 12% 0f tax=",sal)
 else:
      print("you are promoted to next level")









enter salary200000
you are promoted to next level


In [ ]:
a=int(input("enter a number"))
for i in range(11,0,-1):
  print(a,"*",i,"=",a*i)

enter a number88
88 * 11 = 968
88 * 10 = 880
88 * 9 = 792
88 * 8 = 704
88 * 7 = 616
88 * 6 = 528
88 * 5 = 440
88 * 4 = 352
88 * 3 = 264
88 * 2 = 176
88 * 1 = 88


In [ ]:
a=int(input("enter a value"))
while(a<5):
    print(a)
    a=(a+1)

enter a value1
1
2
3
4


In [ ]:
a=[1,4,"nani",'$']
a.insert(1,"barca")
for i in a:
  print(i)

1
barca
4
nani
$


In [ ]:
lis=[4,5,"mani",'#']
lis[2]="vinin"
print(lis)
print(lis[::1])

[4, 5, 'vinin', '#']
[4, 5, 'vinin', '#']


In [ ]:
l1=[2,4,5,"mani",'*']
l2=[4,5,6,"vinin",'w']
l1.extend(l2)
print(l1)
print(len(l1))

[2, 4, 5, 'mani', '*', 4, 5, 6, 'vinin', 'w']
10


In [ ]:
a=[1,"grizu",'c',True]
a.append("mani")
a.insert(2,"vinin")
for i in a:
  print(i)

1
grizu
vinin
c
True
mani


In [ ]:
l1=[2,4,5,"miami"]
l1.clear()
print(l1)

[]


In [ ]:
#create a list of 10 integer elements print there squares save these squares into new list
l1=[1,2,3,4,5,6,7,8,9,10]
l2=[]
for i in l1:
  l2.append(i*i)
print(l2)


[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [ ]:
l1=[2,3,4,5,6,7,8,9,11]
l2=[i*i for i in l1]
print(l2)

[4, 9, 16, 25, 36, 49, 64, 81, 121]


In [ ]:
l1=[i for i in range(1,11)]
l2=[i*i for i in l1 if(i<11)]
print(l2)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [ ]:
#lc
#newlist=[(st of if) if (cond) else (st of else) for ]
l=[23,67,12,34,69]
l1=[i*i if(i>50) else 'x' for i in l]
print(l1)

['x', 4489, 'x', 'x', 4761]


In [ ]:
#take the salary from user if salary <50K 10%tax otherwise 15%tax
a=int(input("enter salary"))
lis=[a-(a*0.1) if(a<=50000) else a-(a*0.15)]
print(lis)

enter salary44444
[39999.6]


In [ ]:
a=[10000,340000,400005,20000]
sal=[i-(i*0.10) if(i<=50) else i-(i*0.15) for i in a]
print(sal)

[8500.0, 289000.0, 340004.25, 17000.0]


In [ ]:
#dictionary
#dictname ={key:value,key:value...}
dict={"mentor":"jwalitha","mentor":'manikanta'}
print(dict)

In [ ]:
dic={1:"markande",2:"vinin",3:'chandu'}
print(dic.keys())

In [ ]:
dict={1:"jashwanth",2:"tharu",3:"chakrawathi"}
print(dict.values())

dict_values(['jashwanth', 'tharu', 'chakrawathi'])


In [ ]:
dict1={"dept":"cse","details":{"YEAR":"IT","sec":"D","count":71}}
print("year is",dict1["details"]["YEAR"])

year is IT


In [ ]:
dict1={2:"MANIKANTA",3:{4:"CSE",5:"tadepalligudem"}}
dict1[2]=1
print(dict1)
print(dict1[3][4])

{2: 1, 3: {4: 'CSE', 5: 'tadepalligudem'}}
CSE


In [ ]:
id=[1,2,3,4]
name=["MANI","VASAVI","KUMAR","LAKSHMI"]
new=dict(zip(id,name))
print(new)

{1: 'MANI', 2: 'VASAVI', 3: 'KUMAR', 4: 'LAKSHMI'}


In [ ]:
a=[1,'NANA','AMMA',2]
b=[2,3,4,5]
x=list(zip(a,b))
print(x)

[(1, 2), ('NANA', 3), ('AMMA', 4), (2, 5)]


In [ ]:
import numpy as np
a=np.array([1,2,3,4]) #1d array
print(a.ndim)
print(a.shape)

1
(4,)


In [ ]:
import numpy as np
a=np.array([[1,2,3],[1,2,3],[1,2,3]]) #2d array
print(a.ndim)
print(a.shape) # 2 rows 2 column
print(a)

2
(3, 3)
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
import numpy as np
b=np.array([[[1,2,3,5],[2,4,5,4]],[[34,5,4,1],[23,12,45,11]]]) #3d array
print(b.ndim)
print(b.shape)
print(b)

3
(2, 2, 4)
[[[ 1  2  3  5]
  [ 2  4  5  4]]

 [[34  5  4  1]
  [23 12 45 11]]]


In [ ]:
import numpy as np
P=np.array([[[1,23,4],[2,3,4]],[[2,34,5],[3,4,2]]]) #3d array
print(P.ndim)
print(P.shape)
print(P)

3
(2, 2, 3)
[[[ 1 23  4]
  [ 2  3  4]]

 [[ 2 34  5]
  [ 3  4  2]]]


In [ ]:
s=np.ones((2,3))
print(s)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
s=np.zeros((2,3,4))
print(s)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
x=np.arange(1,10,2)#2 is steps
print(x)

[1 3 5 7 9]


In [ ]:
#print all the numbers that are divisible by 8 using arrange b/w 1 and 1000 numbers
a=np.arange(8,1001,8)#start,stop,steps
print(a)

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [ ]:
#LINESPACE::SPLITTING RANGE INTO N NUMBERS HAVING COMMON DIFFERENCE

z=np.linspace(2,5,15)
print(z)

[2.         2.21428571 2.42857143 2.64285714 2.85714286 3.07142857
 3.28571429 3.5        3.71428571 3.92857143 4.14285714 4.35714286
 4.57142857 4.78571429 5.        ]


In [ ]:
#tuples and sets,documentation,qr code task

In [ ]:
 import numpy as np
 a=np.arange(1,222,10)
 print(a)

[  1  11  21  31  41  51  61  71  81  91 101 111 121 131 141 151 161 171
 181 191 201 211 221]


In [ ]:
q=np.ones((2,3))
print(q)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
set1={1,2,3,4,5,4}
print(set1)

{1, 2, 3, 4, 5}


In [ ]:
s1={1,23.4,4,"data"}
s2={2,3,4,5}
s3=set(zip(s1,s2))
print(s3)

{(4, 4), (1, 2), (23.4, 5), ('data', 3)}


In [ ]:
set1={1,3,3,3,"enny","zaka"}
set1.add(88)
print(set1)

{1, 3, 'enny', 88, 'zaka'}


In [ ]:
set1={2,3,4,5}
set2={}
print(type(set1))
print(type(set2))

<class 'set'>
<class 'dict'>


In [ ]:
set1={12,3,5,6}
set2=set()
print(type(set1))
print(type(set2))

<class 'set'>
<class 'set'>


In [ ]:
#tuple
t1=(2,3,4,"badoni","mirzin")
print(len(t1))

5


In [ ]:
t1=(2,4,5,6,4)
t2=(1,9,7,3)
t3=t1+t1
print(t3)

(2, 4, 5, 6, 4, 2, 4, 5, 6, 4)


In [ ]:
t1=(1,2,3,4,5,6,2,2)
print(t1.count(2))
print(t1.index(5))
print(min(t1))
print(max(t1))


In [1]:
a=[994,666,443,531,2345]
a.sort()
print(a)

[443, 531, 666, 994, 2345]


In [3]:
a=[344,566,11,2,4,5] #sort and sorted is have in lists only
b=sorted(a)
print(b)

[2, 4, 5, 11, 344, 566]
